# Generated by Django 4.2.13 on 2024-05-22 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="author",
            new_name="user_author",
        ),
    ]
