# Generated by Django 4.2.13 on 2024-05-22 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_rename_author_post_user_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="user_author",
            new_name="user",
        ),
    ]
